In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
n = 100

In [3]:
sieve = [True] * (n + 1)

In [4]:
len(sieve)

101

In [26]:
# 1.0 Identifying primes
# loop for numbers in range 2 (the smallest prime and the number selected)
# Starting with i = 2, i * any number 'j' will result in a non-prime
# We take the resulting multiple of i * 

# Resetting Sieve
sieve = [True] * (n + 1)

for i in range(2, n+1):
    multiple = i
    while True: 
        multiple += i
        print(f'i = {i}, Multiple = {multiple}')
        if multiple > n:
            print("Over 100, break")
            print("************************")
            break
        print(f'Setting {multiple} to False')
        sieve[multiple] = False
[n for n in range(2, n+1) if sieve[n]]

i = 2, Multiple = 4
Setting 4 to False
i = 2, Multiple = 6
Setting 6 to False
i = 2, Multiple = 8
Setting 8 to False
i = 2, Multiple = 10
Setting 10 to False
i = 2, Multiple = 12
Setting 12 to False
i = 2, Multiple = 14
Setting 14 to False
i = 2, Multiple = 16
Setting 16 to False
i = 2, Multiple = 18
Setting 18 to False
i = 2, Multiple = 20
Setting 20 to False
i = 2, Multiple = 22
Setting 22 to False
i = 2, Multiple = 24
Setting 24 to False
i = 2, Multiple = 26
Setting 26 to False
i = 2, Multiple = 28
Setting 28 to False
i = 2, Multiple = 30
Setting 30 to False
i = 2, Multiple = 32
Setting 32 to False
i = 2, Multiple = 34
Setting 34 to False
i = 2, Multiple = 36
Setting 36 to False
i = 2, Multiple = 38
Setting 38 to False
i = 2, Multiple = 40
Setting 40 to False
i = 2, Multiple = 42
Setting 42 to False
i = 2, Multiple = 44
Setting 44 to False
i = 2, Multiple = 46
Setting 46 to False
i = 2, Multiple = 48
Setting 48 to False
i = 2, Multiple = 50
Setting 50 to False
i = 2, Multiple = 52
Setting 52 to False
i = 2, Multiple = 54
Setting 54 to False
i = 2, Multiple = 56
Setting 56 to False
i = 2, Multiple = 58
Setting 58 to False
i = 2, Multiple = 60
Setting 60 to False
i = 2, Multiple = 62
Setting 62 to False
i = 2, Multiple = 64
Setting 64 to False
i = 2, Multiple = 66
Setting 66 to False
i = 2, Multiple = 68
Setting 68 to False
i = 2, Multiple = 70
Setting 70 to False
i = 2, Multiple = 72
Setting 72 to False
i = 2, Multiple = 74
Setting 74 to False
i = 2, Multiple = 76
Setting 76 to False
i = 2, Multiple = 78
Setting 78 to False
i = 2, Multiple = 80
Setting 80 to False
i = 2, Multiple = 82
Setting 82 to False
i = 2, Multiple = 84
Setting 84 to False
i = 2, Multiple = 86
Setting 86 to False
i = 2, Multiple = 88
Setting 88 to False
i = 2, Multiple = 90
Setting 90 to False
i = 2, Multiple = 92
Setting 92 to False
i = 2, Multiple = 94
Setting 94 to False
i = 2, Multiple = 96
Setting 96 to False
i = 2, Multiple = 98
Setting 98 to False
i = 2, Multiple = 100
Setting 100 to False
i = 2, Multiple = 102
Over 100, break
************************
i = 3, Multiple = 6
Setting 6 to False
i = 3, Multiple = 9
Setting 9 to False
i = 3, Multiple = 12
Setting 12 to False
i = 3, Multiple = 15
Setting 15 to False
i = 3, Multiple = 18
Setting 18 to False
i = 3, Multiple = 21
Setting 21 to False
i = 3, Multiple = 24
Setting 24 to False
i = 3, Multiple = 27
Setting 27 to False
i = 3, Multiple = 30
Setting 30 to False
i = 3, Multiple = 33
Setting 33 to False
i = 3, Multiple = 36
Setting 36 to False
i = 3, Multiple = 39
Setting 39 to False
i = 3, Multiple = 42
Setting 42 to False
i = 3, Multiple = 45
Setting 45 to False
i = 3, Multiple = 48
Setting 48 to False
i = 3, Multiple = 51
Setting 51 to False
i = 3, Multiple = 54
Setting 54 to False
i = 3, Multiple = 57
Setting 57 to False
i = 3, Multiple = 60
Setting 60 to False
i = 3, Multiple = 63
Setting 63 to False
i = 3, Multiple = 66
Setting 66 to False
i = 3, Multiple = 69
Setting 69 to False
i = 3, Multiple = 72
Setting 72 to False
i = 3, Multiple = 75
Setting 75 to False
i = 3, Multiple = 78
Setting 78 to False
i = 3, Multiple = 81
Setting 81 to False
i = 3, Multiple = 84
Setting 84 to False
i = 3, Multiple = 87
Setting 87 to False
i = 3, Multiple = 90
Setting 90 to False
i = 3, Multiple = 93
Setting 93 to False
i = 3, Multiple = 96
Setting 96 to False
i = 3, Multiple = 99
Setting 99 to False
i = 3, Multiple = 102
Over 100, break
************************
i = 4, Multiple = 8
Setting 8 to False
i = 4, Multiple = 12
Setting 12 to False
i = 4, Multiple = 16
Setting 16 to False
i = 4, Multiple = 20
Setting 20 to False
i = 4, Multiple = 24
Setting 24 to False
i = 4, Multiple = 28
Setting 28 to False
i = 4, Multiple = 32
Setting 32 to False
i = 4, Multiple = 36
Setting 36 to False
i = 4, Multiple = 40
Setting 40 to False
i = 4, Multiple = 44
Setting 44 to False
i = 4, Multiple = 48
Setting 48 to False
i = 4, Multiple = 52
Setting 52 to False
i = 4, Multiple = 56
Setting 56 to False
i = 4, Multiple = 60
Setting 60 to False
i = 4, Multiple = 64
Setting 64 to False
i = 4, Multiple = 68
Setting 68 to False
i = 4, Multiple = 72
Setting 72 to False
i = 4, Multiple = 76
Setting 76 to False
i = 4, Multiple = 80
Setting 80 to False
i = 4, Multiple = 84
Setting 84 to False
i = 4, Multiple = 88
Setting 88 to False
i = 4, Multiple = 92
Setting 92 to False
i = 4, Multiple = 96
Setting 96 to False
i = 4, Multiple = 100
Setting 100 to False
i = 4, Multiple = 104
Over 100, break
************************
i = 5, Multiple = 10
Setting 10 to False
i = 5, Multiple = 15
Setting 15 to False
i = 5, Multiple = 20
Setting 20 to False
i = 5, Multiple = 25
Setting 25 to False
i = 5, Multiple = 30
Setting 30 to False
i = 5, Multiple = 35
Setting 35 to False
i = 5, Multiple = 40
Setting 40 to False
i = 5, Multiple = 45
Setting 45 to False
i = 5, Multiple = 50
Setting 50 to False
i = 5, Multiple = 55
Setting 55 to False
i = 5, Multiple = 60
Setting 60 to False
i = 5, Multiple = 65
Setting 65 to False
i = 5, Multiple = 70
Setting 70 to False
i = 5, Multiple = 75
Setting 75 to False
i = 5, Multiple = 80
Setting 80 to False
i = 5, Multiple = 85
Setting 85 to False
i = 5, Multiple = 90
Setting 90 to False
i = 5, Multiple = 95
Setting 95 to False
i = 5, Multiple = 100
Setting 100 to False
i = 5, Multiple = 105
Over 100, break
************************
i = 6, Multiple = 12
Setting 12 to False
i = 6, Multiple = 18
Setting 18 to False
i = 6, Multiple = 24
Setting 24 to False
i = 6, Multiple = 30
Setting 30 to False
i = 6, Multiple = 36
Setting 36 to False
i = 6, Multiple = 42
Setting 42 to False
i = 6, Multiple = 48
Setting 48 to False
i = 6, Multiple = 54
Setting 54 to False
i = 6, Multiple = 60
Setting 60 to False
i = 6, Multiple = 66
Setting 66 to False
i = 6, Multiple = 72
Setting 72 to False
i = 6, Multiple = 78
Setting 78 to False
i = 6, Multiple = 84
Setting 84 to False
i = 6, Multiple = 90
Setting 90 to False
i = 6, Multiple = 96
Setting 96 to False
i = 6, Multiple = 102
Over 100, break
************************
i = 7, Multiple = 14
Setting 14 to False
i = 7, Multiple = 21
Setting 21 to False
i = 7, Multiple = 28
Setting 28 to False
i = 7, Multiple = 35
Setting 35 to False
i = 7, Multiple = 42
Setting 42 to False
i = 7, Multiple = 49
Setting 49 to False
i = 7, Multiple = 56
Setting 56 to False
i = 7, Multiple = 63
Setting 63 to False
i = 7, Multiple = 70
Setting 70 to False
i = 7, Multiple = 77
Setting 77 to False
i = 7, Multiple = 84
Setting 84 to False
i = 7, Multiple = 91
Setting 91 to False
i = 7, Multiple = 98
Setting 98 to False
i = 7, Multiple = 105
Over 100, break
************************
i = 8, Multiple = 16
Setting 16 to False
i = 8, Multiple = 24
Setting 24 to False
i = 8, Multiple = 32
Setting 32 to False
i = 8, Multiple = 40
Setting 40 to False
i = 8, Multiple = 48
Setting 48 to False
i = 8, Multiple = 56
Setting 56 to False
i = 8, Multiple = 64
Setting 64 to False
i = 8, Multiple = 72
Setting 72 to False
i = 8, Multiple = 80
Setting 80 to False
i = 8, Multiple = 88
Setting 88 to False
i = 8, Multiple = 96
Setting 96 to False
i = 8, Multiple = 104
Over 100, break
************************
i = 9, Multiple = 18
Setting 18 to False
i = 9, Multiple = 27
Setting 27 to False
i = 9, Multiple = 36
Setting 36 to False
i = 9, Multiple = 45
Setting 45 to False
i = 9, Multiple = 54
Setting 54 to False
i = 9, Multiple = 63
Setting 63 to False
i = 9, Multiple = 72
Setting 72 to False
i = 9, Multiple = 81
Setting 81 to False
i = 9, Multiple = 90
Setting 90 to False
i = 9, Multiple = 99
Setting 99 to False
i = 9, Multiple = 108
Over 100, break
************************
i = 10, Multiple = 20
Setting 20 to False
i = 10, Multiple = 30
Setting 30 to False
i = 10, Multiple = 40
Setting 40 to False
i = 10, Multiple = 50
Setting 50 to False
i = 10, Multiple = 60
Setting 60 to False
i = 10, Multiple = 70
Setting 70 to False
i = 10, Multiple = 80
Setting 80 to False
i = 10, Multiple = 90
Setting 90 to False
i = 10, Multiple = 100
Setting 100 to False
i = 10, Multiple = 110
Over 100, break
************************
i = 11, Multiple = 22
Setting 22 to False
i = 11, Multiple = 33
Setting 33 to False
i = 11, Multiple = 44
Setting 44 to False
i = 11, Multiple = 55
Setting 55 to False
i = 11, Multiple = 66
Setting 66 to False
i = 11, Multiple = 77
Setting 77 to False
i = 11, Multiple = 88
Setting 88 to False
i = 11, Multiple = 99
Setting 99 to False
i = 11, Multiple = 110
Over 100, break
************************
i = 12, Multiple = 24
Setting 24 to False
i = 12, Multiple = 36
Setting 36 to False
i = 12, Multiple = 48
Setting 48 to False
i = 12, Multiple = 60
Setting 60 to False
i = 12, Multiple = 72
Setting 72 to False
i = 12, Multiple = 84
Setting 84 to False
i = 12, Multiple = 96
Setting 96 to False
i = 12, Multiple = 108
Over 100, break
************************
i = 13, Multiple = 26
Setting 26 to False
i = 13, Multiple = 39
Setting 39 to False
i = 13, Multiple = 52
Setting 52 to False
i = 13, Multiple = 65
Setting 65 to False
i = 13, Multiple = 78
Setting 78 to False
i = 13, Multiple = 91
Setting 91 to False
i = 13, Multiple = 104
Over 100, break
************************
i = 14, Multiple = 28
Setting 28 to False
i = 14, Multiple = 42
Setting 42 to False
i = 14, Multiple = 56
Setting 56 to False
i = 14, Multiple = 70
Setting 70 to False
i = 14, Multiple = 84
Setting 84 to False
i = 14, Multiple = 98
Setting 98 to False
i = 14, Multiple = 112
Over 100, break
************************
i = 15, Multiple = 30
Setting 30 to False
i = 15, Multiple = 45
Setting 45 to False
i = 15, Multiple = 60
Setting 60 to False
i = 15, Multiple = 75
Setting 75 to False
i = 15, Multiple = 90
Setting 90 to False
i = 15, Multiple = 105
Over 100, break
************************
i = 16, Multiple = 32
Setting 32 to False
i = 16, Multiple = 48
Setting 48 to False
i = 16, Multiple = 64
Setting 64 to False
i = 16, Multiple = 80
Setting 80 to False
i = 16, Multiple = 96
Setting 96 to False
i = 16, Multiple = 112
Over 100, break
************************
i = 17, Multiple = 34
Setting 34 to False
i = 17, Multiple = 51
Setting 51 to False
i = 17, Multiple = 68
Setting 68 to False
i = 17, Multiple = 85
Setting 85 to False
i = 17, Multiple = 102
Over 100, break
************************
i = 18, Multiple = 36
Setting 36 to False
i = 18, Multiple = 54
Setting 54 to False
i = 18, Multiple = 72
Setting 72 to False
i = 18, Multiple = 90
Setting 90 to False
i = 18, Multiple = 108
Over 100, break
************************
i = 19, Multiple = 38
Setting 38 to False
i = 19, Multiple = 57
Setting 57 to False
i = 19, Multiple = 76
Setting 76 to False
i = 19, Multiple = 95
Setting 95 to False
i = 19, Multiple = 114
Over 100, break
************************
i = 20, Multiple = 40
Setting 40 to False
i = 20, Multiple = 60
Setting 60 to False
i = 20, Multiple = 80
Setting 80 to False
i = 20, Multiple = 100
Setting 100 to False
i = 20, Multiple = 120
Over 100, break
************************
i = 21, Multiple = 42
Setting 42 to False
i = 21, Multiple = 63
Setting 63 to False
i = 21, Multiple = 84
Setting 84 to False
i = 21, Multiple = 105
Over 100, break
************************
i = 22, Multiple = 44
Setting 44 to False
i = 22, Multiple = 66
Setting 66 to False
i = 22, Multiple = 88
Setting 88 to False
i = 22, Multiple = 110
Over 100, break
************************
i = 23, Multiple = 46
Setting 46 to False
i = 23, Multiple = 69
Setting 69 to False
i = 23, Multiple = 92
Setting 92 to False
i = 23, Multiple = 115
Over 100, break
************************
i = 24, Multiple = 48
Setting 48 to False
i = 24, Multiple = 72
Setting 72 to False
i = 24, Multiple = 96
Setting 96 to False
i = 24, Multiple = 120
Over 100, break
************************
i = 25, Multiple = 50
Setting 50 to False
i = 25, Multiple = 75
Setting 75 to False
i = 25, Multiple = 100
Setting 100 to False
i = 25, Multiple = 125
Over 100, break
************************
i = 26, Multiple = 52
Setting 52 to False
i = 26, Multiple = 78
Setting 78 to False
i = 26, Multiple = 104
Over 100, break
************************
i = 27, Multiple = 54
Setting 54 to False
i = 27, Multiple = 81
Setting 81 to False
i = 27, Multiple = 108
Over 100, break
************************
i = 28, Multiple = 56
Setting 56 to False
i = 28, Multiple = 84
Setting 84 to False
i = 28, Multiple = 112
Over 100, break
************************
i = 29, Multiple = 58
Setting 58 to False
i = 29, Multiple = 87
Setting 87 to False
i = 29, Multiple = 116
Over 100, break
************************
i = 30, Multiple = 60
Setting 60 to False
i = 30, Multiple = 90
Setting 90 to False
i = 30, Multiple = 120
Over 100, break
************************
i = 31, Multiple = 62
Setting 62 to False
i = 31, Multiple = 93
Setting 93 to False
i = 31, Multiple = 124
Over 100, break
************************
i = 32, Multiple = 64
Setting 64 to False
i = 32, Multiple = 96
Setting 96 to False
i = 32, Multiple = 128
Over 100, break
************************
i = 33, Multiple = 66
Setting 66 to False
i = 33, Multiple = 99
Setting 99 to False
i = 33, Multiple = 132
Over 100, break
************************
i = 34, Multiple = 68
Setting 68 to False
i = 34, Multiple = 102
Over 100, break
************************
i = 35, Multiple = 70
Setting 70 to False
i = 35, Multiple = 105
Over 100, break
************************
i = 36, Multiple = 72
Setting 72 to False
i = 36, Multiple = 108
Over 100, break
************************
i = 37, Multiple = 74
Setting 74 to False
i = 37, Multiple = 111
Over 100, break
************************
i = 38, Multiple = 76
Setting 76 to False
i = 38, Multiple = 114
Over 100, break
************************
i = 39, Multiple = 78
Setting 78 to False
i = 39, Multiple = 117
Over 100, break
************************
i = 40, Multiple = 80
Setting 80 to False
i = 40, Multiple = 120
Over 100, break
************************
i = 41, Multiple = 82
Setting 82 to False
i = 41, Multiple = 123
Over 100, break
************************
i = 42, Multiple = 84
Setting 84 to False
i = 42, Multiple = 126
Over 100, break
************************
i = 43, Multiple = 86
Setting 86 to False
i = 43, Multiple = 129
Over 100, break
************************
i = 44, Multiple = 88
Setting 88 to False
i = 44, Multiple = 132
Over 100, break
************************
i = 45, Multiple = 90
Setting 90 to False
i = 45, Multiple = 135
Over 100, break
************************
i = 46, Multiple = 92
Setting 92 to False
i = 46, Multiple = 138
Over 100, break
************************
i = 47, Multiple = 94
Setting 94 to False
i = 47, Multiple = 141
Over 100, break
************************
i = 48, Multiple = 96
Setting 96 to False
i = 48, Multiple = 144
Over 100, break
************************
i = 49, Multiple = 98
Setting 98 to False
i = 49, Multiple = 147
Over 100, break
************************
i = 50, Multiple = 100
Setting 100 to False
i = 50, Multiple = 150
Over 100, break
************************
i = 51, Multiple = 102
Over 100, break
************************
i = 52, Multiple = 104
Over 100, break
************************
i = 53, Multiple = 106
Over 100, break
************************
i = 54, Multiple = 108
Over 100, break
************************
i = 55, Multiple = 110
Over 100, break
************************
i = 56, Multiple = 112
Over 100, break
************************
i = 57, Multiple = 114
Over 100, break
************************
i = 58, Multiple = 116
Over 100, break
************************
i = 59, Multiple = 118
Over 100, break
************************
i = 60, Multiple = 120
Over 100, break
************************
i = 61, Multiple = 122
Over 100, break
************************
i = 62, Multiple = 124
Over 100, break
************************
i = 63, Multiple = 126
Over 100, break
************************
i = 64, Multiple = 128
Over 100, break
************************
i = 65, Multiple = 130
Over 100, break
************************
i = 66, Multiple = 132
Over 100, break
************************
i = 67, Multiple = 134
Over 100, break
************************
i = 68, Multiple = 136
Over 100, break
************************
i = 69, Multiple = 138
Over 100, break
************************
i = 70, Multiple = 140
Over 100, break
************************
i = 71, Multiple = 142
Over 100, break
************************
i = 72, Multiple = 144
Over 100, break
************************
i = 73, Multiple = 146
Over 100, break
************************
i = 74, Multiple = 148
Over 100, break
************************
i = 75, Multiple = 150
Over 100, break
************************
i = 76, Multiple = 152
Over 100, break
************************
i = 77, Multiple = 154
Over 100, break
************************
i = 78, Multiple = 156
Over 100, break
************************
i = 79, Multiple = 158
Over 100, break
************************
i = 80, Multiple = 160
Over 100, break
************************
i = 81, Multiple = 162
Over 100, break
************************
i = 82, Multiple = 164
Over 100, break
************************
i = 83, Multiple = 166
Over 100, break
************************
i = 84, Multiple = 168
Over 100, break
************************
i = 85, Multiple = 170
Over 100, break
************************
i = 86, Multiple = 172
Over 100, break
************************
i = 87, Multiple = 174
Over 100, break
************************
i = 88, Multiple = 176
Over 100, break
************************
i = 89, Multiple = 178
Over 100, break
************************
i = 90, Multiple = 180
Over 100, break
************************
i = 91, Multiple = 182
Over 100, break
************************
i = 92, Multiple = 184
Over 100, break
************************
i = 93, Multiple = 186
Over 100, break
************************
i = 94, Multiple = 188
Over 100, break
************************
i = 95, Multiple = 190
Over 100, break
************************
i = 96, Multiple = 192
Over 100, break
************************
i = 97, Multiple = 194
Over 100, break
************************
i = 98, Multiple = 196
Over 100, break
************************
i = 99, Multiple = 198
Over 100, break
************************
i = 100, Multiple = 200
Over 100, break
************************

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

In [33]:
# Resetting Sieve
sieve = [True] * (n + 1)

# Using updated notation
for i in range(2, n+1):
    for multiple in range(i*2, n+1, i):
        sieve[multiple] = False

# Printing result
[n for n in range(2, n+1) if sieve[n]]

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

In [53]:
from math import sqrt
n = 14

# Resetting Sieve
sieve = [True] * (n + 1)

# Using updated notation
for i in range(2, round(sqrt(n)+1)):
    if sieve[i] is False:
        # Makes our code more efficient by removing numbers where they are already non primes
        # E.g. we don't need to check multiples of 4 when we have already checked 2
        continue
    for multiple in range(i*2, n+1, i):
        sieve[multiple] = False

# Printing result
[n for n in range(2, n+1) if sieve[n]]

[2, 3, 5, 7, 11, 13]

In [36]:
# Non perfect squares will give errors
# Perfect squares e.g. 4, 9 
for i in range(2, 20):
    print(f'{i}, {sqrt(i)**2}, {round(sqrt(i)**2)}')

2, 2.0000000000000004, 2
3, 2.9999999999999996, 3
4, 4.0, 4
5, 5.000000000000001, 5
6, 5.999999999999999, 6
7, 7.000000000000001, 7
8, 8.000000000000002, 8
9, 9.0, 9
10, 10.000000000000002, 10
11, 11.0, 11
12, 11.999999999999998, 12
13, 12.999999999999998, 13
14, 14.0, 14
15, 15.000000000000002, 15
16, 16.0, 16
17, 17.0, 17
18, 17.999999999999996, 18
19, 19.000000000000004, 19

In [37]:
2.0317 * 10 **-32

2.0316999999999998e-32

In [45]:
sqrt(14)

3.7416573867739413

In [47]:
round(sqrt(14))

4

In [55]:
from math import sqrt
n = 100

# Resetting Sieve
sieve = [True] * (n + 1)

# Using updated notation
for i in range(2, round(sqrt(n)+1)):
    if sieve[i] is False:
        # Makes our code more efficient by removing numbers where they are already non primes
        # E.g. we don't need to check multiples of 4 when we have already checked 2
        continue
    for multiple in range(i*i, n+1, i):
        sieve[multiple] = False

# Printing result
[n for n in range(2, n+1) if sieve[n]]

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

In [105]:
def primes_up_to(n):
    sieve = [True] * (n + 1)
    
    for i in range(2, round(sqrt(n)+1)):
        if sieve[i] is False:
            continue
        for multiple in range(i*i, n+1, i):
            sieve[multiple] = False
    
    # Printing result
    # [n for n in range(2, n+1) if sieve[n]]

In [67]:
_ = primes_up_to(10_000_000)

In [82]:
from timeit import timeit
timeit('list(range(100))', number=1)

4.317000275477767e-06

In [75]:
help(timeit)

Help on function timeit in module timeit:

timeit(stmt='pass', setup='pass', timer=<built-in function perf_counter>, number=1000000, globals=None)
    Convenience function to create Timer object and call timeit method.

In [91]:
def f():
    return 0
def g():
    return 0

In [92]:
timeit('f(); g()', globals={'f': f, 'g': g})

0.10712960400269367

In [94]:
timeit('f(); g()', globals=globals())

0.10635044597438537

In [96]:
timeit('primes_up_to(100)', globals=globals(), number=1)

1.3746001059189439e-05

In [97]:
%timeit f()

59.2 ns ± 0.905 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [108]:
%timeit primes_up_to(100)

5.6 µs ± 26 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [106]:
def primes_up_to_inefficient(n):
    sieve = [True] * (n + 1)
    
    for i in range(2, round(sqrt(n)+1)):
#         if sieve[i] is False:
#             continue
        for multiple in range(i*2, n+1, i):
            sieve[multiple] = False
    
    # Printing result
    # [n for n in range(2, n+1) if sieve[n]]

In [107]:
%timeit primes_up_to_inefficient(100)

9 µs ± 86.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [110]:
%timeit -n 1_000 -r 20 primes_up_to(100)

5.73 µs ± 144 ns per loop (mean ± std. dev. of 20 runs, 1,000 loops each)